# Generated by Django 5.2.7 on 2026-03-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_usercard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercard',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='usercard',
            name='razorpay_payment_id',
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
