# Generated by Django 6.0.3 on 2026-04-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_productsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_alt_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
